### ISSUE TITLE
Please, submit 1.9.74 to pypi

### ISSUE THREAD

**Issue by mbello** [zdohnal/pycups#7]
I do not know how it works to get new releases available on pypi, but would you check why 1.9.74 is not available there? Thanks!

**Comment by mbello** [comment]
Would you please?

**Comment by zdohnal** [comment]
Hi Marcelo,
I currently have a issue with uploading it - it seems gpg has an issue with my key (it seems you need to have gpg key to upload to pypi). It ends with error:

error: command 'gpg' failed with exit status 2
make: *** [Makefile:33: upload] Error 1

So I don't know when I get into solving it. I'll contact previous owner of project, if he has any advice.

**Comment by mbello** [comment]
If your dist folder has all the packages correctly generated, you can manually upload it using twine. Should take only a few minutes (and no need to deal with gpg signatures. See here:

https://packaging.python.org/tutorials/packaging-projects/#uploading-your-project-to-pypi

**Comment by mbello** [comment]
I believe if you take the -s parameter out of:

upload:
	$(PYTHON) setup.py sdist $(SDIST_ARGS) upload **-s**

It should skip GPG signing and would work. From what I know, GPG signing is not required.

**Comment by zdohnal** [comment]
Hmm... I really need to solve that gpg key issue, but this one I release without signature...

**Comment by zdohnal** [comment]
It should be on pypi now.
